Restrict pwn to channel
riscv-rust/gd32vf103xx-hal pull request #29
Opened 2020-11-22 00:27 UTC by elionne

Restrict PWM Channel to their corresponding pin.

Now you cannot specify a pin to the wrong PWN Channel.

2020-11-22 13:59 UTC, Disasm requested changes
Thank you!
I noticed that remap information is missing, both regular and remapped pins are used in the same way. This will not work unless you remap them explicitly outside of the driver. It's better to set this remap configuration in the driver itself to prevent related mistakes.

2020-11-23 11:28 UTC, elionne commented
Hello,

Ok let me rework with remap feature.

2020-12-20 13:59 UTC, Disasm requested changes
Thank you! However, a few more changes are needed :)

I was also thinking if it's possible to make an API like this:
```rust
let pwm = PwmTimer::new(timer0, (None, Some(pa9), Some(pa10), None), &mut rcu, &mut afio);
```
This should be possible with a sort of `Pins<TIMER>` trait implemented for the tuple. Anyway, I'm happy to merge this PR as is after the fixes :)

2020-12-20 13:59 UTC, Disasm commented on src/pwm.rs
> +        PartialRemap2: [ch0: PA0, ch1: PA1, ch2: PB10, ch3: PB1 ],
```suggestion
        PartialRemap2: [ch0: PA0, ch1: PA1, ch2: PB10, ch3: PB11 ],
```

2020-12-20 13:59 UTC, Disasm commented on src/pwm.rs
> +                    Channel::NotUsed => {},
Hmm, this `NotUsed` variant doesn't look right here

2020-12-20 14:10 UTC, Disasm commented
Oh, I've just found another problem:
```rust
let pwm_t0 = PwmConfiguration::<TIMER0, NoRemap>::new(dp.TIMER0, &mut afio);
let (_, ch1, ch2, _) = pwm_t0.pins(None, Some(&pa9), Some(&pa10), None);
let mut pwm_t0 = pwm_t0.configure(&mut rcu);

pa9.into_push_pull_output().set_high();
pwm_t0.set_duty(ch1, 100); // Oops!
```

2021-01-21 22:34 UTC, elionne commented
Hello I finally did the rework with the suggest API. Now the code is simpler and API nicer. Thanks for that suggestion. Sorry for the delay.

2021-03-24 19:37 UTC, dkhayes117 commented
Interesting work, @elionne.  Looking forward for this to be merged.

2021-08-26 14:28 UTC, dkhayes117 commented
Appreciate the work!  I will try to get everything reviewed later today :)

2021-08-30 22:56 UTC, dkhayes117 approved these changes

2021-08-30 23:08 UTC, dkhayes117 commented
Thank you for your work!

2021-08-30 23:09 UTC, dkhayes117 commented
Oops, my mistake pushed the wrong button.

2021-08-30 23:12 UTC, merged